[Feat] 관리자의 이슈 삭제 기능을 구현한다.
10aeat/10aeat_Backend pull request #148
Opened 2024-06-03 11:02 UTC by asd42270

# Pull Request 요약

- 이슈 삭제 기능 구현

## 변경 사항

- 우선 물리 삭제로 구현했습니다!
- 추후 리팩토링을 고려하여 논리 삭제 코드는 주석으로 남겨두었습니다.

## 관련 이슈

- #145 

## 개발 유형

- [ ] 버그 수정
- [ ] 새로운 기능 개발
- [ ] 리팩토링
- [ ] 테스트 코드 작성
- [ ] 문서 업데이트
- 기타 (아래에 설명 추가)

## 작업 기간

- 작업 시작일: (2024-06-03)
- 작업 종료일: (2024-06-03)

## 유의사항

- 이슈 수정은 내일 오전 or 오늘 밤 중으로 올릴게유...

## 참고문헌

- 이 PR을 작성하며 참조한 문헌이나 가이드가 있다면 여기에 링크를 추가하세요.

2024-06-03 14:47 UTC, ghrltjdtprbs requested changes
수고하셨습니다! 일단 내일 오전까지 이슈 히스토리 기능 구현여부 나온다니까 일단 pr 머지하지 마시고 여기서 수정하면 좋을 것 같습니당 😊😊

2024-06-03 14:47 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
> +public class ArticleIssue extends SoftDeletableBaseTimeEntity {
SoftDeletableBaseTimeEntity 는 왜 추가하셨는지 궁금합니다!

2024-06-03 14:47 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
> +    public void setUpdatedAt(LocalDateTime currentTime) {this.updatedAt = currentTime;}
이렇게 임의로 설정을 안해도 쿼리 변동시 updateAt이 자동으로 갱신됩니다!

2024-06-03 14:47 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
> +    Optional<ArticleIssue> findByIdAndDeletedAtIsNull(Long id);
현재 이슈 히스토리가 추가될지 안될지 모르는 상황이라 DeletedAtIsNull 검증은 불필요한 것 같습니다!

2024-06-03 14:47 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
> +    Optional<ArticleIssue> findFirstByManageArticleAndDeletedAtIsNullOrderByCreatedAtDesc(ManageArticle manageArticle);
mysql에는 AutoIncrement 기능이 있으니 id를 기준으로 desc 를 수행하면 성능이 더 좋아진다는 점 참고해주세요!

2024-06-03 14:49 UTC, asd42270 commented on src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
> +public class ArticleIssue extends SoftDeletableBaseTimeEntity {
아 초기에 논리 삭제 때문에 상속 받았었습니다!!

2024-06-03 14:49 UTC, asd42270 commented on src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
> +    public void setUpdatedAt(LocalDateTime currentTime) {this.updatedAt = currentTime;}
오 넵넵!!!

2024-06-03 14:50 UTC, Galmaeki approved these changes
고생하셨습니다!

2024-06-03 14:50 UTC, Galmaeki commented on src/docs/asciidoc/articleissue/issuedelete-api.adoc
> += Issue Delete REST API Docs
기존 이슈 페이지랑 합쳐도 좋을것같슴다

2024-06-03 14:50 UTC, Galmaeki commented on src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
> +    Optional<ArticleIssue> findFirstByManageArticleAndDeletedAtIsNullOrderByCreatedAtDesc(ManageArticle manageArticle);
보충해서 설명하면 mySql은 기본적으로 ID 기준으로 인덱싱을 진행하기 때문에 인덱싱이 안된 CreateAt보다 좋은 성능이 나옵니다

2024-06-03 14:50 UTC, asd42270 commented on src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
> +    Optional<ArticleIssue> findByIdAndDeletedAtIsNull(Long id);
아 넵 알겠습니다!!

2024-06-03 14:50 UTC, asd42270 commented on src/docs/asciidoc/articleissue/issuedelete-api.adoc
> += Issue Delete REST API Docs
아 맞네요!! 알겠습니다!

2024-06-03 14:51 UTC, asd42270 commented on src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
> +    Optional<ArticleIssue> findFirstByManageArticleAndDeletedAtIsNullOrderByCreatedAtDesc(ManageArticle manageArticle);
넵 감사합니다!!

2024-06-04 14:29 UTC, ghrltjdtprbs approved these changes

2024-06-04 14:29 UTC, merged