[Feat#22] Security 설정을 한다.
10aeat/10aeat_Backend pull request #27
Opened 2024-05-01 09:44 UTC by asd42270

# Pull Request 요약

- 주요 변경 사항에 대한 간단한 설명을 여기에 작성하세요.
- @Galmaeki 목요일 작성 예정입니다!

## 변경 사항

- 이 PR의 코드 주요 내용은 무엇인가요?

## 관련 이슈

- #22 

## 개발 유형

- [ ] 버그 수정
- [ ] 새로운 기능 개발
- [ ] 리팩토링
- [ ] 테스트 코드 작성
- [ ] 문서 업데이트
- 기타 (아래에 설명 추가)

## 작업 기간

- 작업 시작일: (YYYY-MM-DD)
- 작업 종료일: (YYYY-MM-DD)

## 유의사항

- 이 PR로부터 발생할 수 있는 유의사항이 있나요? 이 PR이 다른 부분에 미칠 수 있는 영향 등을 설명하세요.

## 참고문헌

- 이 PR을 작성하며 참조한 문헌이나 가이드가 있다면 여기에 링크를 추가하세요.

2024-05-02 02:14 UTC, Galmaeki commented
Pr 문서화 완료했습니다
이슈 문서화 예정이며 부족한 부분 지적해주세요!

2024-05-02 07:28 UTC, ghrltjdtprbs requested changes
수고하셨습니다! 코드 보고 몇 가지 개선 사항을 남겨뒀으니 참고해주세요!

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
> +    @PostMapping("/register")
URI를 동작이 아닌 자원을 지칭하도록 변경하면 좀 더  RESTful 한 설계가 될 것 같습니다!

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/dto/request/MemberRegisterRequestDto.java
> +public record MemberRegisterRequestDto(
DTO에 record를 사용하셨네요! record 를 사용하시면 코드가 간결해지고 데이터의 불변성을 보장하니 좋은 선택인 것 같습니다 ㅎㅎ 👍👍
아시겠지만 record 클래스에도  @Email, @NotBlank, @Size  같은 Hibernate Validator 사용이 가능하니 유효성 검사 로직을 추가해 보시는건 어떨까요?

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/dto/request/MemberRequestDto.java
> +
마찬가지로 유효성 검사 로직을 추가하면 좋을 것 같습니다.😊 
그리고 현재 DTO 클래스들의 이름이 의미를 잘 전달하고 있지만, 두 개의 DTO 의 차이를 좀 더 명확하게 하기 위해LoginRequestDto, RegisterRequestDto 등으로 변경하시는 것은 어떨까요?

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/entity/Member.java
> +}
코드 스타일 통일하는건 어떨까요?

1. 메서드 선언의 맨 위와 아래는 줄바꿈 X
2. 클래스 선언의 맨 위는 줄바꿈 O, 맨 아래는 줄바꿈 X
3. 파일의 맨 아래에 줄바꿈 삽입 

맨 아래 개행이 필요한 이유: https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/exception/MemberNotExistException.java
> +
코드스타일 관련 위 리뷰와 동일합니다.😊

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/repository/MemberRepository.java
> +
개행에 신경써주세요! 커밋 전 줄정렬을 해주거나 한 번 더 체크하면 더 깔끔한 코드가 됩니다 ㅎㅎ👍

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/repository/MemberRepository.java
> +    default Member loadUserByUsername(String email){
loadUserByUsername 메서드가 현재 인터페이스 내에 정의되어 있지만, 프로젝트의 전체 구조를 고려하여 서비스 계층 또는 유틸리티 클래스로 분리하는 것도 고려해 볼 수 있을 것 같습니다! 
이는 인터페이스의 선언적 역할을 유지하면서도, 메서드의 재사용성을 높일 수 있습니다.😊

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/global/config/SecurityConfig.java
서비스 계층을 더 세분화하여 AuthenticationService와 같은 별도의 서비스로 분리하는 것을 고려해 보시는 건 어떠신가요? 이는 전체 서비스 계층의 역할을 더 명확하게 하고, 코드의 유지보수성을 높일 수 있습니다! 하지만 그냥 제안이니 이대로 진행하셔도 상관없습니다! 👍👍
+개행도...

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/service/MemberService.java
> +public class MemberService {
클래스 레벨에 트랜잭션을 적용하면 좋을 것 같습니다!
아시겠지만, 트랜젝션을 적용하면 데이터베이스에 대한 일련의 작업을 하나의 단위로 묶어 처리하고 ACID 원칙을 보장한다는 장점이 있습니다 ㅎㅎ 
또한 읽기 전용 트랜젝션으로 성능 향상도 노려볼 수 있습니다 👍

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/global/security/principal/MemberPrincipalService.java
> +public class MemberPrincipalService {
클래스 이름이 MemberPrincipalService인데, 이는 서비스 계층과의 혼동이 있을 수 있습니다. 클래스의 목적과 기능을 반영한 이름으로 변경하는 것이 좋습니다. 
예를 들어, MemberDetailsProvider 또는 UserDetailsProvider와 같은 이름은 어떨까요?

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/global/security/principal/MemberPrincipalService.java
> +    public UserDetails loadUserByUsername(String email){
loadUserByUsername 메서드가 스프링 시큐리티의 UserDetailsService 인터페이스의 메서드와 동일한 기능을 수행하는 것 같네요! 
이 부분을 명시적으로 구현하여 클래스의 구조를 명확히 하고, 스프링 시큐리티와의 통합을 강화하는건 어떨까요? 
예를 들어, MemberPrincipalService 클래스가 UserDetailsService 인터페이스를 직접 구현하고, 해당 메서드를 재정의하도록 변경할 수 있습니다.😊
```java
@Override
    public UserDetails loadUserByUsername(String email) {
        return new MemberPrincipal(memberRepository.loadUserByUsername(email));
    }
```
이렇게 하면 클래스가 스프링 시큐리티의 구조에 직접 통합되며, 인증 및 권한 부여 관련 로직을 더 쉽게 유지 관리할 수 있습니다.👍👍

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/global/exception/ErrorCode.java
제가 ErrorCode 사용법을 제대로 알려드리지 못한 것 같습니다! 
프로젝트에서 다루는 예외가 대부분 클라이언트 에러이므로, HTTP 상태 코드 기반의 분류는 추적이 어렵습니다. 그렇기 때문에 도메인 중심으로 분류하는 것을 추천드려요! ( //4xx -> // MEMBER)

2024-05-02 07:28 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/global/exception/ErrorCode.java
> +    MEMBER_NOT_EXIST(HttpStatus.FORBIDDEN, "존재하지 않는 사용자입니다."),
**MEMBER_NOT_EXIST :** 
Forbidden은 주로 사용자에게 해당 리소스에 접근할 권한이 없을 때 사용됩니다. 그러나 "존재하지 않는 사용자" 상황에서는 404 Not Found가 더 적절할 수 있습니다. 이는 해당 사용자가 존재하지 않아 리소스를 찾을 수 없다는 의미로 해석될 수 있습니다.

**TOKEN_NOT_FOUND :** 
Unauthorized는 토큰을 통해 사용자 인증이 필요하나, 토큰이 없거나 잘못된 경우 사용되는 코드입니다. 그러므로 "토큰을 찾을 수 없다"는 상황에서는 Unauthorized가 더 적절할 것 같습니다! 😊

2024-05-02 07:39 UTC, ghrltjdtprbs commented
추가로 pr 컨벤션과 브랜치 컨벤션에 대해 리뷰 남깁니다! 
pr 컨벤션은 커밋 컨벤션과 동일하게 이슈 번호 필요없이 [Feat] 만 붙여주세면 됩니다! 
브랜치는 " feature/#이슈 번호" 입니다! 참고로 hotfix는 이슈번호 필요없이  hotfix로만 사용하시면 됩니다! 
(feat#22 -> feature/22)

Backend Convention : https://github.com/orgs/10aeat/discussions/3

2024-05-02 07:49 UTC, ghrltjdtprbs requested changes

2024-05-02 07:49 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/member/entity/Member.java
> +public class Member extends BaseTimeEntity {
회원 정보는 무조건 soft delete기능이 들어갑니다! SoftDeletableBaseTimeEntity 를 이용해주세요 ㅎㅎ 😊

2024-05-05 07:10 UTC, ghrltjdtprbs approved these changes
변경사항 확인했습니다! 수고하셨어요ㅎㅎ 👍👍

2024-05-07 07:06 UTC, Galmaeki requested changes
리뷰사항 남겨놨습니다!
확인 부탁드려요!

2024-05-07 07:06 UTC, Galmaeki commented on src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
> +@RequiredArgsConstructor
```java
@RequestMaping("/members")
```
중복되는 경로는 묶어줘도 좋을 것 같습니다

2024-05-07 07:13 UTC, asd42270 commented on src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
> +@RequiredArgsConstructor
수정했습니다~~~

2024-05-07 08:42 UTC, Galmaeki approved these changes
수고하셨습니다

2024-05-07 08:42 UTC, merged