[Feature] 관리자 회원가입, 로그인 기능을 구현한다.
10aeat/10aeat_Backend pull request #83
Opened 2024-05-20 16:17 UTC by ghrltjdtprbs

## ⭐️ [Feature] 관리자 회원가입, 로그인 기능을 구현한다.

- 관리자 회원가입을 구현하였습니다.
- 관리자 로그인을 구현하였습니다.
- REST Docs 문서화를 구현하였습니다. 

## 관련 이슈

- #81 

## 개발 유형

- [ ] 버그 수정
- [ ] 새로운 기능 개발
- [ ] 리팩토링
- [ ] 테스트 코드 작성
- [ ] 문서 업데이트

## 작업 기간

- 작업 시작일: (2024-05-20)
- 작업 종료일: (2024-05-21)

2024-05-20 16:40 UTC, Galmaeki requested changes
고생 많으셨습니다!
코멘트 확인 부탁드리겠슴다!

2024-05-20 16:40 UTC, Galmaeki commented on src/main/java/com/final_10aeat/global/config/SecurityConfig.java
> +                        "/admin").permitAll()
뒤에 와일드카드 없어도 허용 되나요?

2024-05-20 16:40 UTC, Galmaeki commented on src/main/java/com/final_10aeat/domain/admin/controller/AdminController.java
> +    public ResponseEntity<ResponseDTO<Void>> registerAdmin(
컨트롤러에서 Admin이 표기되어있으니 register만 사용해도 좋다고 생각합니다

2024-05-20 16:40 UTC, Galmaeki commented on src/main/java/com/final_10aeat/domain/admin/controller/AdminController.java
> +        @RequestBody @Valid MemberLoginRequestDto request) {
MemberLoginRequestDto를 common이나 global로 빼도 좋을것 같습니다!

2024-05-20 16:40 UTC, Galmaeki commented on src/main/java/com/final_10aeat/domain/admin/dto/request/CreateAdminRequestDto.java
> +    @Email(message = "이메일 형식이 유효하지 않습니다.")
Email 어노테이션은 null이 허용됩니다!
DB단에서도 막히긴 하지만 NotBlank도 같이 사용해주셨으면 좋을 것 같습니다

2024-05-20 16:40 UTC, Galmaeki commented on src/main/java/com/final_10aeat/domain/admin/service/AdminService.java
> +    public Admin registerAdmin(CreateAdminRequestDto request) {
이부분도 Admin이 Class이름에 존재하니 Admin을 제거해도 좋을것같습니다

2024-05-20 16:40 UTC, Galmaeki commented on src/main/java/com/final_10aeat/domain/admin/service/AdminService.java
> +        if (adminRepository.findByEmail(email).isPresent()) {
existByEmail을 사용하지 않은 이유가 있을까요?

2024-05-20 16:40 UTC, Galmaeki commented on src/test/java/com/final_10aeat/domain/admin/AdminControllerDocsTest.java
> +        when(adminService.registerAdmin(registerRequest)).thenReturn(null);
이 부분은 메소드 이름은 when이지만 given 부분입니다!
아래 주석을 // When & Then 으로 사용하는게 더 BDD 패턴에 맞는 사용법입니다

2024-05-21 05:41 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/admin/controller/AdminController.java
> +        @RequestBody @Valid MemberLoginRequestDto request) {
제 개인적인 생각으로는 로그인에서 두 번 사용이 끝이고, 앞으로 사용 가능성이 없기 때문에 따로 빼기에는 부적절한 것 같습니다!

2024-05-21 05:41 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/admin/service/AdminService.java
> +        if (adminRepository.findByEmail(email).isPresent()) {
Optional을 사용하여 이메일의 존재 여부를 확인하고 예외를 던지는 방식은 명확하고 일관된 예외 처리를 가능하게 합니다! 
그리고 현재 로직에서는 findByEmail을 사용해도 성능에 큰 차이가 없고, 후에 admin로직의 findByEmail을 사용할 일이 생길 것 같아 existByEmail 대신 findByEmail를 사용하였습니다! 👍👍

2024-05-21 05:41 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/global/config/SecurityConfig.java
> +                        "/admin").permitAll()
관리자 관련 api 경로에 전부 /admin이 붙어서 일부러 "/admin"로 명시하였습니다. 😊

2024-05-21 05:41 UTC, ghrltjdtprbs commented on src/test/java/com/final_10aeat/domain/admin/AdminControllerDocsTest.java
> +        when(adminService.registerAdmin(registerRequest)).thenReturn(null);
수정해서 커밋했습니다! 지적 감사합니다 ㅎㅎ😊
관련 커밋 : f053bdbd80c0f8ad13c1bb2a48d6ef5aed774245

2024-05-21 05:41 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/admin/controller/AdminController.java
> +    public ResponseEntity<ResponseDTO<Void>> registerAdmin(
생각해보니 그게 더 깔끔할 것 같네요! 수정해서 커밋했으니 확인해주세요 ㅎㅎ
관련 커밋 : 43ab74f0629e505b2781b35717ba6445ba926bce

2024-05-21 05:41 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/admin/service/AdminService.java
> +    public Admin registerAdmin(CreateAdminRequestDto request) {
수정해서 커밋했습니다! 😊
관련 커밋 : 43ab74f0629e505b2781b35717ba6445ba926bce

2024-05-21 05:41 UTC, ghrltjdtprbs commented on src/main/java/com/final_10aeat/domain/admin/dto/request/CreateAdminRequestDto.java
> +    @Email(message = "이메일 형식이 유효하지 않습니다.")
모르고 있었네요... 좋은 정보 감사합니다! 수정했으니 확인해주세요!
관련 커밋 : 76c9e8a950209b02b0d0d46745d682a7a221086e

2024-05-21 05:50 UTC, asd42270 approved these changes
고생하셨습니다!!! 재현님이 다 말씀해 주신 것 같아서 저는 딱히 없는 것 같아욤

2024-05-21 05:55 UTC, Galmaeki approved these changes
고생 많으셨슴다!

2024-05-21 05:56 UTC, merged